export const SectionIds = {
  "initial-consonants": "initial-consonants",
  "initial-consonants-like-english": "initial-consonants-like-english",
  "initial-consonants-like-english-2": "initial-consonants-like-english-2",
  sibilants: "sibilants",
  "initial-consonants-not-found-in-english":
    "initial-consonants-not-found-in-english",
  "dental-vs-retroflex-stops": "dental-vs-retroflex-stops",
  "on-sound-changes": "on-sound-changes",
  "a-note-on-voiced-sounds": "a-note-on-voiced-sounds",
  dentilabialization: "dentilabialization",
  denasalization: "denasalization",
  "final-consonants": "final-consonants",
  vowels: "vowels",
  "kan-on": "kan-on",
  "japanese-vowels": "japanese-vowels",
  caveats: "caveats",
  finals: "finals",
  "structure-of-finals": "structure-of-finals",
  medials: "medials",
  coda: "coda",
  "main-vowels": "main-vowels",
  tones: "tones",
  "a-finals": "a-finals",
  "e-finals": "e-finals",
  "i-finals": "i-finals",
  "o-finals": "o-finals",
  "u-finals": "u-finals",
  diacritics: "diacritics",
  "four-rows": "four-rows",
  "four-divisions": "four-divisions",
  "go-on": "go-on",
  "kan-on-diacritics": "kan-on-diacritics",
  baxter: "baxter",
  references: "references",
};
